name: Build Darwin SwiftUI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-13
    timeout-minutes: 20
    env:
      APPLE_DEV_CERT: ${{ secrets.APPLE_DEV_CERT }}
      KEYCHAIN_PASSWORD: ${{ secrets.APPLE_DEV_CERT_PWD }}
      P12_PASSWORD: ${{ secrets.APPLE_DEV_CERT_PWD }}
      CI_SKIP_SIGNING: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Xcode version
        run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

      - name: Print xcodebuild version
        run: |
          xcodebuild -version
          sudo ls -1 /Applications | grep "Xcode"

      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_15.0.app/Contents/Developer'

      - name: Install the Apple certificate
        run: |
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          echo -n "$APPLE_DEV_CERT" | base64 --decode -o $CERTIFICATE_PATH
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

      - name: List keychain contents
        run: security find-identity -v -p codesigning

      - name: Unlock keychain
        run: security unlock-keychain -p actions $RUNNER_TEMP/app-signing.keychain-db

      - name: Build the App for x86_64
        run: xcodebuild -project NexodusAgentApp.xcodeproj -scheme NexodusAgentApp
        working-directory: darwin

      - name: Build the Helper for x86_64
        run: xcodebuild -project NexodusAgentApp.xcodeproj -scheme NexodusAgentHelper
        working-directory: darwin
