name: build darwin xcode/swift

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Xcode version
        run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

      # First run, ignore failure due to generated file launchd.plist build race condition
      #- name: Build the App for x86_64 (First Run)
        #run: xcodebuild -project "NexodusAgentApp.xcodeproj" -scheme "NexodusAgentHelper" -configuration Debug -destination 'platform=macOS,arch=x86_64' CODE_SIGNING_ALLOWED=NO
        #working-directory: darwin/nexd-darwin-gui
        #continue-on-error: true # Ignore this failure

      - name: Build the App for x86_64 (Second Run)
        run: xcodebuild -project "NexodusAgentApp.xcodeproj" -scheme "NexodusAgentHelper" -configuration Debug -destination 'platform=macOS,arch=x86_64' CODE_SIGNING_ALLOWED=NO
        working-directory: darwin/nexd-darwin-gui

      # First run, ignore failure due to generated file launchd.plist build race condition
      #- name: Build the App for x86_64 (First Run)
       # run: xcodebuild -project "NexodusAgentApp.xcodeproj" -scheme "NexodusAgentApp" -configuration Debug -destination 'platform=macOS,arch=x86_64' CODE_SIGNING_ALLOWED=NO
        #working-directory: darwin/nexd-darwin-gui
        #continue-on-error: true # Ignore this failure

      - name: Build the App for x86_64 (Second Run)
        run: xcodebuild -project "NexodusAgentApp.xcodeproj" -scheme "NexodusAgentApp" -configuration Debug -destination 'platform=macOS,arch=x86_64' CODE_SIGNING_ALLOWED=NO
        working-directory: darwin/nexd-darwin-gui
