name: Build Darwin SwiftUI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    env:
      APPLE_DEV_CERT: ${{ secrets.APPLE_DEV_CERT }}


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Xcode version
        run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

      - name: Debug Check if the APPLE_DEV_CERT environment variable is empty
        run: |
          if [ -z "$APPLE_DEV_CERT" ]; then
            echo "APPLE_DEV_CERT environment variable is empty"
          else
            echo "APPLE_DEV_CERT environment variable is set"
          fi

      - name: Import Apple Development credentials
        run: |
          echo $APPLE_DEV_CERT | base64 --decode --output certificate.p12
          security create-keychain -p password123 build.keychain
          security unlock-keychain -p password123 build.keychain
          security import certificate.p12 -k build.keychain -P "password123" -T /usr/bin/codesign
          security list-keychains -s build.keychain
          security default-keychain -s build.keychain

      - name: List keychain contents
        run: security find-identity -v -p codesigning

      - name: Unlock keychain
        run: security unlock-keychain -p actions build.keychain

      - name: Build the App for x86_64
        run: xcodebuild -project NexodusAgentApp.xcodeproj -scheme NexodusAgentApp -configuration Debug -destination 'platform=macOS,arch=x86_64'
        working-directory: darwin

      - name: Build the Helper for x86_64
        run: xcodebuild -project NexodusAgentApp.xcodeproj -scheme NexodusAgentHelper -configuration Debug -destination 'platform=macOS,arch=x86_64'
        working-directory: darwin
